apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  type: LoadBalancer
  selector:
    app: binarycalculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
